In [2]:
import pandas as pd

In [9]:
data = pd.read_csv('data/data_context/data_with_context.csv')
data["c1_context"] = None
data["c2_context"] = None
data
data.to_csv('data/data_context/data_with_context.csv', index=False)

In [5]:
data.to_excel('./data/train_large.xlsx', index=False)

## Fill No Desc in Data Done

In [27]:
file_path = 'data/data_context/data_done.csv'

with open(file_path, 'r', encoding='utf-8') as file:
    for i, line in enumerate(file, start=1):  # Mulai menghitung dari baris ke-1
        if i == 1685:  # Jika baris yang dicari adalah 1685
            print(f"Baris {i}: {line}")
            break  # Setelah baris ditemukan, hentikan loop

Baris 1685: bina nusantara university,"Bina Nusantara University, also known as BINUS UNIVERSITY, is a private university in Indonesia. The main campus of the university is located in Kebon Jeruk, West Jakarta. Most of its campuses are located within the area of Greater Jakarta Region. It also has campuses at Bandung, Malang, and Semarang.",Bina Nusantara,"BINUS

In [34]:
data_done = pd.read_csv('data/data_context/data_done.csv', on_bad_lines='skip')
data_with_context = pd.read_json('data/data_context/data_with_context.jsonl', lines=True)

In [35]:
data_done

,c1,c1_context,c2,c2_context,match_type
0,pt. amerta indah otsuka,PT Amerta Indah Otsuka is affiliation from Ots...,pt amarta indah otsuka,PT Amerta Indah Otsuka is affiliation from Ots...,Match
1,pt. amerta indah otsuka,PT Amerta Indah Otsuka is affiliation from Ots...,pt amerta indah tuska,PT Amerta Indah Otsuka is affiliation from Ots...,Match
2,pt. amerta indah otsuka,PT Amerta Indah Otsuka is affiliation from Ots...,amerta indah otsuka,Company overview\r\nPT Amerta Indah Otsuka (AI...,Match
3,pt. amerta indah otsuka,PT Amerta Indah Otsuka is affiliation from Ots...,amerta indah otska,Company overview\r\nPT Amerta Indah Otsuka (AI...,Match
4,pt. amerta indah otsuka,PT Amerta Indah Otsuka is affiliation from Ots...,pt amerta indahotsuka,PT Amerta Indah Otsuka is affiliation from Ots...,Match
...,...,...,...,...,...
149,pt. indonesia oppo electronics,"Find company research, competitor information,...",indonesia oppo,"Indonesia OPPO Electronics, the local unit of ...",Match
150,pt. indonesia oppo electronics,"Find company research, competitor information,...",pt oppo electronics,ms Oppo; my Oppo; ne ओप्पो इलेक्ट्रानिक्स; nl ...,Match
151,pt. indonesia oppo electronics,"Find company research, competitor information,...",indonesia o e,"India Bank Intl Indonesia: OE: Postage, Telegr...",Match
152,pt. indonesia oppo electronics,"Find company research, competitor information,...",oppo electronics,OPPO Electronics Corporation is an electronics...,Match
153,pt. indonesia oppo electronics,"Find company research, competitor information,...",pt indonesia oppo,"Find company research, competitor information,...",Match

In [30]:
data_with_context

,c1,c1_context,c2,c2_context,match_type
0,anz,ANZ Group Holdings Ltd (ANZ) is a provider of ...,ANZ,ANZ Group Holdings Ltd (ANZ) is a provider of ...,Match
1,anz,ANZ Group Holdings Ltd (ANZ) is a provider of ...,Australian New Zealand Banking Group,"The Australian New Zealand Banking Group, is a...",Match
2,anz,ANZ Group Holdings Ltd (ANZ) is a provider of ...,A.N.Z.,"ANZ provides research, transaction services, f...",Match
3,anz,ANZ Group Holdings Ltd (ANZ) is a provider of ...,ANZ Bank,The Australia and New Zealand Banking Group Li...,Match
4,anz,ANZ Group Holdings Ltd (ANZ) is a provider of ...,Anz,ANZ Group Holdings Ltd (ANZ) is a provider of ...,Match
...,...,...,...,...,...
32556,michigan state university,Michigan State University is the nation's prem...,University of Michigan,University of Michigan operates as an educatio...,Non-Match
32557,michigan state university,Michigan State University is the nation's prem...,Michigan Technological University,Michigan Technological University is a flagshi...,Non-Match
32558,michigan state university,Michigan State University is the nation's prem...,Michigan State College,Founded in 1855 on the ideals of democratizati...,Non-Match
32559,michigan state university,Michigan State University is the nation's prem...,Central Michigan University,Central Michigan University is a leading publi...,Non-Match
32560,michigan state university,Michigan State University is the nation's prem...,Michigan State Police,The Michigan State Police (MSP) is a full-serv...,Non-Match

In [36]:
def update_context(data_done, data_with_context):
    for index, row in data_done.iterrows():
        # Jika c1_context adalah 'No Desc', cari nilainya di data_with_context berdasarkan c1 dan c2
        if row['c1_context'] == 'No Desc':
            matched_row = data_with_context[(data_with_context['c1'] == row['c1']) & (data_with_context['c2'] == row['c2'])]
            if not matched_row.empty:
                data_done.at[index, 'c1_context'] = matched_row['c1_context'].values[0]

        # Jika c2_context adalah 'No Desc', cari nilainya di data_with_context berdasarkan c1 dan c2
        if row['c2_context'] == 'No Desc':
            matched_row = data_with_context[(data_with_context['c1'] == row['c1']) & (data_with_context['c2'] == row['c2'])]
            if not matched_row.empty:
                data_done.at[index, 'c2_context'] = matched_row['c2_context'].values[0]

# Jalankan fungsi untuk mengupdate data_done
update_context(data_done, data_with_context)

In [37]:
data_done.to_csv('data/data_context/temp.csv', index=False)
data_done.to_json('data/data_context/temp.jsonl', orient='records', lines=True)

In [33]:
data_done

,c1,c1_context,c2,c2_context,match_type
0,asian paints,Asian Paints Limited manufactures a wide range...,Asian Paints,Asian Paints Limited manufactures a wide range...,Match
1,asian paints,Asian Paints Limited manufactures a wide range...,Asian Paints Ltd.,Asian Paints Limited manufactures a wide range...,Match
2,asian paints,Asian Paints Limited manufactures a wide range...,Asian Paint Ltd,Asian Paints is India's largest paint manufact...,Match
3,asian paints,Asian Paints Limited manufactures a wide range...,AsianPaints,Asian Paints Limited manufactures a wide range...,Match
4,asian paints,Asian Paints Limited manufactures a wide range...,Asn Paints,"Find company research, competitor information,...",Match
...,...,...,...,...,...
1678,pt. bussan auto finance,PT. Bussan Auto Finance provides automotive fi...,pt bussan autofinance,PT. Bussan Auto Finance provides automotive fi...,Match
1679,pt. bussan auto finance,PT. Bussan Auto Finance provides automotive fi...,pt bussan auto finance indonesia,PT BUSSAN AUTO FINANCE is an active company re...,Match
1680,pt. bussan auto finance,PT. Bussan Auto Finance provides automotive fi...,bussan auto,Bussan Auto Finance provides automotive financ...,Match
1681,pt. bussan auto finance,PT. Bussan Auto Finance provides automotive fi...,busan auto finance,Bussan Auto Finance provides automotive financ...,Match
1682,pt. bussan auto finance,PT. Bussan Auto Finance provides automotive fi...,opt bussan auto finance,PT. Bussan Auto Finance provides automotive fi...,Match